version: 0.0
os: linux
files:
  - source: /
    destination: /home/express/DemoExpressApp
    overwrite: true
hooks:
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/app-start.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/app-stop.sh
      timeout: 300
      runas: ec2-user